import type { Metadata } from "next";
import { Cuprum } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/store/storeProvidert";
import { Popup } from "@/components/popup/Popup";


const cuprum = Cuprum({
  variable: "--font-cuprum",
  subsets: ["cyrillic"],
  weight: ['400', '500', '600', '700',]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${cuprum.variable}`}>
        <StoreProvider>
        <Popup/>  
        {children}
        </StoreProvider>
      </body>
    </html>
  );
}
